version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_dc
    volumes:
      - /c/Users/WilsonCai/WilsonPrivate/dockerData/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres #在此填写postgres的用户名
      POSTGRES_DB: postgres #在此填写postgres的数据库名，默认是postgres
      POSTGRES_PASSWORD: 123456 #在此填写posgres的数据库密码
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_dc
    environment: 
      PGADMIN_DEFAULT_EMAIL: user@domain.com #在此填写pgAdmin登录账户邮箱
      PGADMIN_DEFAULT_PASSWORD: SuperSecret #在此填写pgAdmin密码
    ports:
      - "5050:80"
volumes:
  pgdata:
    
