version: "3"

services:
  zookeeper:
    image: zookeeper
    build:
      context: ./
    container_name: zookeeper
    ports:
      - 12181:2181
    volumes:
      - zookeeper_data:/data
      - zookeeper_data:/datalog
      - zookeeper_data:/logs
    restart: always

  kafka_node_0:
    depends_on:
      - zookeeper
    build:
      context: ./
    container_name: kafka-node-0
    image: wurstmeister/kafka
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: host.docker.internal:12181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:19092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:19092
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
    ports:
      - 19092:19092
    volumes:
      - kafka_node_0:/kafka
    restart: unless-stopped

  kafka_node_1:
    depends_on:
      - kafka_node_0
    build:
      context: ./
    container_name: kafka-node-1
    image: wurstmeister/kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: host.docker.internal:12181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:19093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:19093
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
    ports:
      - 19093:19093
    volumes:
      - kafka_node_1:/kafka
    restart: unless-stopped

  kafka_node_2:
    depends_on:
      - kafka_node_1
    build:
      context: ./
    container_name: kafka-node-2
    image: wurstmeister/kafka
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: host.docker.internal:12181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:19094
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:19094
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
    ports:
      - 19094:19094
    volumes:
      - kafka_node_2:/kafka
    restart: unless-stopped

volumes:
  zookeeper_data:
    driver: local
  kafka_node_0:
    driver: local
  kafka_node_1:
    driver: local
  kafka_node_2:
    driver: local