apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-app
  name: node-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: node-app