version: '3.8'

services:
  emqx:
    image: emqx:latest
    container_name: emqx
    restart: unless-stopped
    ports:
      - "1883:1883"   # MQTT 协议
      - "8883:8883"   # MQTT over TLS
      - "8083:8083"   # WebSocket
      - "8084:8084"   # WebSocket over TLS
      - "18083:18083" # Dashboard 管理界面
    environment:
      - EMQX_NODE__NAME=emqx@127.0.0.1
      - EMQX_NODE__COOKIE=mysecretcookie
