apiVersion: v1
kind: Service
metadata:
  name: exposing-service0
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/instance: kafka-service
    app.kubernetes.io/name: kafka
    statefulset.kubernetes.io/pod-name: kafka-service-0
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092

--- 
apiVersion: v1
kind: Service
metadata:
  name: exposing-service1
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/instance: kafka-service
    app.kubernetes.io/name: kafka
    statefulset.kubernetes.io/pod-name: kafka-service-1
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
--- 
apiVersion: v1
kind: Service
metadata:
  name: exposing-service2
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/instance: kafka-service
    app.kubernetes.io/name: kafka
    statefulset.kubernetes.io/pod-name: kafka-service-2
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
--- 
apiVersion: v1
kind: Service
metadata:
  name: exposing-service3
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: zookeeper
    app.kubernetes.io/instance: kafka-service
    app.kubernetes.io/name: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181

---
apiVersion: v1
kind: Service
metadata:
  name: exposing-kowl
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: kafka-ui
    app.kubernetes.io/name: kowl
    pod-template-hash: 86d6c8755c
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8080









