DROP TABLE IF EXISTS ld1557 CASCADE;
CREATE TABLE ld1557
(
    id                SERIAL       NOT NULL,
    "chassisId"       VARCHAR(255) NOT NULL,
    created_by        INTEGER,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by        INTEGER,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone          DATE         NOT NULL,
    "timeStampAtZone" VARCHAR(255),
    "timeZone"        VARCHAR(255),
    "timeStamp"       VARCHAR(255),
    "processedAt"     VARCHAR(255),
    "totalLoggedTime" INTEGER,
    time_bt0n5        INTEGER,
    time_bt5n10       INTEGER,
    time_bt10n15      INTEGER,
    time_bt15n20      INTEGER,
    time_bt20n25      INTEGER,
    time_bt25n30      INTEGER,
    time_bt30n35      INTEGER,
    time_bt35n40      INTEGER,
    time_bt40n45      INTEGER,
    time_bt45n50      INTEGER,
    time_bt50n55      INTEGER,
    time_bt55n60      INTEGER,
    time_bt60n65      INTEGER,
    time_bt65n70      INTEGER,
    time_bt70n75      INTEGER,
    time_bt75n80      INTEGER,
    time_bt80n85      INTEGER,
    time_bt85n90      INTEGER,
    time_bt90n95      INTEGER,
    time_bt95n100     INTEGER
);
COMMENT
ON TABLE ld1557 IS 'Traction battery SoC distribution (full range)';

DROP TABLE IF EXISTS ld1544 CASCADE;
CREATE TABLE ld1544
(
    id                SERIAL       NOT NULL,
    "chassisId"       VARCHAR(255) NOT NULL,
    created_by        INTEGER,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by        INTEGER,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone          DATE         NOT NULL,
    "timeStampAtZone" VARCHAR(255),
    "timeZone"        VARCHAR(255),
    "timeStamp"       VARCHAR(255),
    "processedAt"     VARCHAR(255),
    "totalLoggedTime" INTEGER,
    "powerRef"        INTEGER,
    "time_bt0n0p5"    INTEGER,
    "time_bt0p5n1"    INTEGER,
    "time_bt1n2"      INTEGER,
    "time_bt2n3"      INTEGER,
    "time_bt3n4"      INTEGER,
    "time_bt4n5"      INTEGER,
    "time_bt5n6"      INTEGER,
    "time_bt6n7"      INTEGER,
    "time_bt7n8"      INTEGER,
    "time_bt8n9"      INTEGER,
    "time_bt9n10"     INTEGER,
    "time_bt10n11"    INTEGER,
    "time_bt11n12"    INTEGER,
    "time_bt12n13"    INTEGER,
    "time_bt13n14"    INTEGER,
    "time_bt14n15"    INTEGER,
    "time_bt15n17p5"  INTEGER,
    "time_bt17p5n20"  INTEGER,
    "time_bt20n22p5"  INTEGER,
    "time_bt22p5n25"  INTEGER,
    "time_bt25n27p5"  INTEGER,
    "time_bt27p5n30"  INTEGER,
    "time_bt30n32p5"  INTEGER,
    "time_bt32p5n35"  INTEGER,
    "time_bt35n37p5"  INTEGER,
    "time_bt37p5n40"  INTEGER,
    "time_bt40n42p5"  INTEGER,
    "time_bt42p5n45"  INTEGER,
    "time_bt45n47p5"  INTEGER,
    "time_bt47p5n50"  INTEGER,
    "time_bt50n55"    INTEGER,
    "time_bt55n60"    INTEGER,
    "time_bt60n65"    INTEGER,
    "time_bt65n70"    INTEGER,
    "time_bt70n75"    INTEGER,
    "time_bt75n80"    INTEGER,
    "time_bt80n85"    INTEGER,
    "time_bt85n90"    INTEGER,
    "time_bt90n95"    INTEGER,
    "time_bt95n100"   INTEGER,
    "time_gt100"      INTEGER
);
COMMENT
ON TABLE ld1544 IS 'Traction battery charging power distribution';

DROP TABLE IF EXISTS ld1556 CASCADE;
CREATE TABLE ld1556
(
    id                SERIAL       NOT NULL,
    "chassisId"       VARCHAR(255) NOT NULL,
    created_by        INTEGER,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by        INTEGER,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone          DATE         NOT NULL,
    "timeStampAtZone" VARCHAR(255),
    "timeZone"        VARCHAR(255),
    "timeStamp"       VARCHAR(255),
    "processedAt"     VARCHAR(255),
    "totalLoggedTime" INTEGER,
    "time_lt0"        INTEGER,
    "time_bt0n5"      INTEGER,
    "time_bt5n10"     INTEGER,
    "time_bt10n15"    INTEGER,
    "time_bt15n20"    INTEGER,
    "time_bt20n25"    INTEGER,
    "time_bt25n30"    INTEGER,
    "time_bt30n35"    INTEGER,
    "time_bt35n40"    INTEGER,
    "time_bt40n45"    INTEGER,
    "time_bt45n50"    INTEGER,
    "time_bt50n55"    INTEGER,
    "time_bt55n60"    INTEGER,
    "time_bt60n65"    INTEGER,
    "time_bt65n70"    INTEGER,
    "time_bt70n75"    INTEGER,
    "time_bt75n80"    INTEGER,
    "time_bt80n85"    INTEGER,
    "time_bt85n90"    INTEGER,
    "time_bt90n95"    INTEGER,
    "time_bt95n100"   INTEGER,
    "time_gt100"      INTEGER
);
COMMENT
ON TABLE ld1556 IS 'Motor temperature distribution (full range)';

DROP TABLE IF EXISTS ld1542 CASCADE;
CREATE TABLE ld1542
(
    id                SERIAL       NOT NULL,
    "chassisId"       VARCHAR(255) NOT NULL,
    created_by        INTEGER,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by        INTEGER,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone          DATE         NOT NULL,
    "timeStampAtZone" VARCHAR(255),
    "timeZone"        VARCHAR(255),
    "timeStamp"       VARCHAR(255),
    "processedAt"     VARCHAR(255),
    "totalLoggedTime" INTEGER,
    "PCC_num"         INTEGER,
    "PCF_num"         INTEGER
);
COMMENT
ON TABLE ld1542 IS 'Precharge events occurences';
COMMENT
ON COLUMN ld1542."PCC_num" IS 'total number of occurences of event “precharge completed”';
COMMENT
ON COLUMN ld1542."PCF_num" IS 'total number of occurences of event “precharge failed”';

DROP TABLE IF EXISTS ld1479 CASCADE;
CREATE TABLE ld1479
(
    id                   SERIAL       NOT NULL,
    "chassisId"          VARCHAR(255) NOT NULL,
    created_by           INTEGER,
    created_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by           INTEGER,
    updated_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone             DATE         NOT NULL,
    "timeStampAtZone"    VARCHAR(255),
    "timeZone"           VARCHAR(255),
    "timeStamp"          VARCHAR(255),
    "processedAt"        VARCHAR(255),
    "totalLoggedTime"    INTEGER,
    "work_time"          INTEGER,
    "idle_time"          INTEGER,
    "excessiveIdle_time" INTEGER
);
COMMENT
ON TABLE ld1479 IS 'Machine utilization';

DROP TABLE IF EXISTS ld1579 CASCADE;
CREATE TABLE ld1579
(
    id                  SERIAL       NOT NULL,
    "chassisId"         VARCHAR(255) NOT NULL,
    created_by          INTEGER,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by          INTEGER,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone            DATE         NOT NULL,
    "timeStampAtZone"   VARCHAR(255),
    "timeZone"          VARCHAR(255),
    "timeStamp"         VARCHAR(255),
    "processedAt"       VARCHAR(255),
    "totalLoggedTime"   INTEGER,
    "time_ecoNotForced" INTEGER,
    "time_ecoForced"    INTEGER,
    "time_normal"       INTEGER,
    "time_boost"        INTEGER
);
COMMENT
ON TABLE ld1579 IS 'Machine work mode distribution';

DROP TABLE IF EXISTS ld1545 CASCADE;
CREATE TABLE ld1545
(
    id                SERIAL       NOT NULL,
    "chassisId"       VARCHAR(255) NOT NULL,
    created_by        INTEGER,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by        INTEGER,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone          DATE         NOT NULL,
    "timeStampAtZone" VARCHAR(255),
    "timeZone"        VARCHAR(255),
    "timeStamp"       VARCHAR(255),
    "processedAt"     VARCHAR(255),
    "totalLoggedTime" INTEGER,
    "powerRef"        INTEGER,
    "time_bt0n0p5"    INTEGER,
    "time_bt0p5n1"    INTEGER,
    "time_bt1n2"      INTEGER,
    "time_bt2n3"      INTEGER,
    "time_bt3n4"      INTEGER,
    "time_bt4n5"      INTEGER,
    "time_bt5n6"      INTEGER,
    "time_bt6n7"      INTEGER,
    "time_bt7n8"      INTEGER,
    "time_bt8n9"      INTEGER,
    "time_bt9n10"     INTEGER,
    "time_bt10n11"    INTEGER,
    "time_bt11n12"    INTEGER,
    "time_bt12n13"    INTEGER,
    "time_bt13n14"    INTEGER,
    "time_bt14n15"    INTEGER,
    "time_bt15n17p5"  INTEGER,
    "time_bt17p5n20"  INTEGER,
    "time_bt20n22p5"  INTEGER,
    "time_bt22p5n25"  INTEGER,
    "time_bt25n27p5"  INTEGER,
    "time_bt27p5n30"  INTEGER,
    "time_bt30n32p5"  INTEGER,
    "time_bt32p5n35"  INTEGER,
    "time_bt35n37p5"  INTEGER,
    "time_bt37p5n40"  INTEGER,
    "time_bt40n42p5"  INTEGER,
    "time_bt42p5n45"  INTEGER,
    "time_bt45n47p5"  INTEGER,
    "time_bt47p5n50"  INTEGER,
    "time_bt50n55"    INTEGER,
    "time_bt55n60"    INTEGER,
    "time_bt60n65"    INTEGER,
    "time_bt65n70"    INTEGER,
    "time_bt70n75"    INTEGER,
    "time_bt75n80"    INTEGER,
    "time_bt80n85"    INTEGER,
    "time_bt85n90"    INTEGER,
    "time_bt90n95"    INTEGER,
    "time_bt95n100"   INTEGER,
    "time_gt100"      INTEGER

);
COMMENT
ON TABLE ld1545 IS 'Traction battery discharging power distribution';

DROP TABLE IF EXISTS ld1552 CASCADE;
CREATE TABLE ld1552
(
    id                SERIAL       NOT NULL,
    "chassisId"       VARCHAR(255) NOT NULL,
    created_by        INTEGER,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by        INTEGER,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone          DATE         NOT NULL,
    "timeStampAtZone" VARCHAR(255),
    "timeZone"        VARCHAR(255),
    "timeStamp"       VARCHAR(255),
    "processedAt"     VARCHAR(255),
    "totalLoggedTime" INTEGER,
    "time_lt0"        INTEGER,
    "time_bt0n5"      INTEGER,
    "time_bt5n10"     INTEGER,
    "time_bt10n15"    INTEGER,
    "time_bt15n20"    INTEGER,
    "time_bt20n25"    INTEGER,
    "time_bt25n30"    INTEGER,
    "time_bt30n35"    INTEGER,
    "time_bt35n40"    INTEGER,
    "time_bt40n45"    INTEGER,
    "time_bt45n50"    INTEGER,
    "time_bt50n55"    INTEGER,
    "time_bt55n60"    INTEGER,
    "time_bt60n65"    INTEGER,
    "time_bt65n70"    INTEGER,
    "time_bt70n75"    INTEGER,
    "time_bt75n80"    INTEGER,
    "time_bt80n85"    INTEGER,
    "time_bt85n90"    INTEGER,
    "time_bt90n95"    INTEGER,
    "time_bt95n100"   INTEGER,
    "time_gt100"      INTEGER

);
COMMENT
ON TABLE ld1552 IS 'Inverter temperature distribution (full range)';

DROP TABLE IF EXISTS ld1541 CASCADE;
CREATE TABLE ld1541
(
    id                 SERIAL       NOT NULL,
    "chassisId"        VARCHAR(255) NOT NULL,
    created_by         INTEGER,
    created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by         INTEGER,
    updated_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone           DATE         NOT NULL,
    "timeStampAtZone"  VARCHAR(255),
    "timeZone"         VARCHAR(255),
    "timeStamp"        VARCHAR(255),
    "processedAt"      VARCHAR(255),
    "totalLoggedTime"  INTEGER,
    "NbMotorStart_ocr" INTEGER,
    "NbMotorStop_ocr"  INTEGER

);
COMMENT
ON TABLE ld1541 IS 'Motor start and stop occurences';

DROP TABLE IF EXISTS ld1526 CASCADE;
CREATE TABLE ld1526
(
    id                      SERIAL       NOT NULL,
    "chassisId"             VARCHAR(255) NOT NULL,
    created_by              INTEGER,
    created_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by              INTEGER,
    updated_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone                DATE         NOT NULL,
    "timeStampAtZone"       VARCHAR(255),
    "timeZone"              VARCHAR(255),
    "timeStamp"             VARCHAR(255),
    "processedAt"           VARCHAR(255),
    "totalLoggedTime"       INTEGER,
    "timeElapsed_eco"       INTEGER,
    "timeElapsed_normal"    INTEGER,
    "timeElapsed_boost"     INTEGER,
    "energyConsumed_eco"    INTEGER,
    "energyConsumed_normal" INTEGER,
    "energyConsumed_boost"  INTEGER

);
COMMENT
ON TABLE ld1526 IS 'Inverter Total Energy Consumed , Working Modes';

DROP TABLE IF EXISTS ld1551 CASCADE;
CREATE TABLE ld1551
(
    id                SERIAL       NOT NULL,
    "chassisId"       VARCHAR(255) NOT NULL,
    created_by        INTEGER,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by        INTEGER,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone          DATE         NOT NULL,
    "timeStampAtZone" VARCHAR(255),
    "timeZone"        VARCHAR(255),
    "timeStamp"       VARCHAR(255),
    "processedAt"     VARCHAR(255),
    "totalLoggedTime" INTEGER,
    "powerReference"  INTEGER,
    "time_bt0n4"      INTEGER,
    "time_bt4n8"      INTEGER,
    "time_bt8n12"     INTEGER,
    "time_bt12n16"    INTEGER,
    "time_bt16n20"    INTEGER,
    "time_bt20n24"    INTEGER,
    "time_bt24n28"    INTEGER,
    "time_bt28n32"    INTEGER,
    "time_bt32n36"    INTEGER,
    "time_bt36n40"    INTEGER,
    "time_bt40n44"    INTEGER,
    "time_bt44n48"    INTEGER,
    "time_bt48n52"    INTEGER,
    "time_bt52n56"    INTEGER,
    "time_bt56n60"    INTEGER,
    "time_bt60n64"    INTEGER,
    "time_bt64n68"    INTEGER,
    "time_bt68n72"    INTEGER,
    "time_bt72n76"    INTEGER,
    "time_bt76n80"    INTEGER,
    "time_bt80n84"    INTEGER,
    "time_bt84n88"    INTEGER,
    "time_bt88n92"    INTEGER,
    "time_bt92n96"    INTEGER,
    "time_bt96n100"   INTEGER,
    "time_gt100"      INTEGER

);
COMMENT
ON TABLE ld1551 IS 'Inverter Power Consumption, Distribution';

DROP TABLE IF EXISTS ld1553 CASCADE;
CREATE TABLE ld1553
(
    id                SERIAL       NOT NULL,
    "chassisId"       VARCHAR(255) NOT NULL,
    created_by        INTEGER,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by        INTEGER,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone          DATE         NOT NULL,
    "timeStampAtZone" VARCHAR(255),
    "timeZone"        VARCHAR(255),
    "timeStamp"       VARCHAR(255),
    "processedAt"     VARCHAR(255),
    "totalLoggedTime" INTEGER,
    "stopped_time"    INTEGER,
    "runIdle_time"    INTEGER,
    "runWork_time"    INTEGER,
    "runTravel_time"  INTEGER

);
COMMENT
ON TABLE ld1553 IS 'Electrical Motor Usage Information';

DROP TABLE IF EXISTS ld1563 CASCADE;
CREATE TABLE ld1563
(
    id                SERIAL       NOT NULL,
    "chassisId"       VARCHAR(255) NOT NULL,
    created_by        INTEGER,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by        INTEGER,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone          DATE         NOT NULL,
    "timeStampAtZone" VARCHAR(255),
    "timeZone"        VARCHAR(255),
    "timeStamp"       VARCHAR(255),
    "processedAt"     VARCHAR(255),
    "totalLoggedTime" INTEGER,
    "ofsTemp"         INTEGER,
    "refTemp"         INTEGER,
    "time_lt80"       INTEGER,
    "time_bt80n81"    INTEGER,
    "time_bt81n82"    INTEGER,
    "time_bt82n83"    INTEGER,
    "time_bt83n84"    INTEGER,
    "time_bt84n85"    INTEGER,
    "time_bt85n86"    INTEGER,
    "time_bt86n87"    INTEGER,
    "time_bt87n88"    INTEGER,
    "time_bt88n89"    INTEGER,
    "time_bt89n90"    INTEGER,
    "time_bt90n91"    INTEGER,
    "time_bt91n92"    INTEGER,
    "time_bt92n93"    INTEGER,
    "time_bt93n94"    INTEGER,
    "time_bt94n95"    INTEGER,
    "time_bt95n96"    INTEGER,
    "time_bt96n97"    INTEGER,
    "time_bt97n98"    INTEGER,
    "time_bt98n99"    INTEGER,
    "time_bt99n100"   INTEGER,
    "time_gt100"      INTEGER

);
COMMENT
ON TABLE ld1563 IS 'Inverter Temperature, High Range, Time Distribution';

DROP TABLE IF EXISTS ld1564 CASCADE;
CREATE TABLE ld1564
(
    id                SERIAL       NOT NULL,
    "chassisId"       VARCHAR(255) NOT NULL,
    created_by        INTEGER,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by        INTEGER,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone          DATE         NOT NULL,
    "timeStampAtZone" VARCHAR(255),
    "timeZone"        VARCHAR(255),
    "timeStamp"       VARCHAR(255),
    "processedAt"     VARCHAR(255),
    "totalLoggedTime" INTEGER,
    "ofsTemp"         INTEGER,
    "refTemp"         INTEGER,
    "time_lt0"        INTEGER,
    "time_bt0n1"      INTEGER,
    "time_bt1n2"      INTEGER,
    "time_bt2n3"      INTEGER,
    "time_bt3n4"      INTEGER,
    "time_bt4n5"      INTEGER,
    "time_bt5n6"      INTEGER,
    "time_bt6n7"      INTEGER,
    "time_bt7n8"      INTEGER,
    "time_bt8n9"      INTEGER,
    "time_bt9n10"     INTEGER,
    "time_bt10n11"    INTEGER,
    "time_bt11n12"    INTEGER,
    "time_bt12n13"    INTEGER,
    "time_bt13n14"    INTEGER,
    "time_bt14n15"    INTEGER,
    "time_bt15n16"    INTEGER,
    "time_bt16n17"    INTEGER,
    "time_bt17n18"    INTEGER,
    "time_bt18n19"    INTEGER,
    "time_bt19n20"    INTEGER,
    "time_gt20"       INTEGER

);
COMMENT
ON TABLE ld1564 IS 'Inverter Temperature, Low Range, Time Distribution';

DROP TABLE IF EXISTS ld1565 CASCADE;
CREATE TABLE ld1565
(
    id                SERIAL       NOT NULL,
    "chassisId"       VARCHAR(255) NOT NULL,
    created_by        INTEGER,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by        INTEGER,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone          DATE         NOT NULL,
    "timeStampAtZone" VARCHAR(255),
    "timeZone"        VARCHAR(255),
    "timeStamp"       VARCHAR(255),
    "processedAt"     VARCHAR(255),
    "totalLoggedTime" INTEGER,
    "num_startReq"    INTEGER,
    "num_mps"         INTEGER,
    "num_ips"         INTEGER,
    "num_tbps"        INTEGER,
    "num_ots"         INTEGER,
    "num_DCDCps"      INTEGER,
    "num_osrh"        INTEGER

);
COMMENT
ON TABLE ld1565 IS 'Electric Motor, Start Request Event, Counter';
COMMENT
ON COLUMN ld1565."num_startReq" IS 'motor start request from operator';
COMMENT
ON COLUMN ld1565."num_mps" IS 'motor start inhibited due to motor protection status';
COMMENT
ON COLUMN ld1565."num_ips" IS 'motor start inhibited due to inverter protection status';
COMMENT
ON COLUMN ld1565."num_tbps" IS 'motor start inhibited due to traction battery protection status';
COMMENT
ON COLUMN ld1565."num_ots" IS 'motor start inhibited due to oil temperature status';
COMMENT
ON COLUMN ld1565."num_DCDCps" IS 'motor start inhibited due to DCDC protection status';
COMMENT
ON COLUMN ld1565."num_osrh" IS 'motor start inhibited due to operator still requesting hydraulic';

DROP TABLE IF EXISTS ld1566 CASCADE;
CREATE TABLE ld1566
(
    id                SERIAL       NOT NULL,
    "chassisId"       VARCHAR(255) NOT NULL,
    created_by        INTEGER,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by        INTEGER,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone          DATE         NOT NULL,
    "timeStampAtZone" VARCHAR(255),
    "timeZone"        VARCHAR(255),
    "timeStamp"       VARCHAR(255),
    "processedAt"     VARCHAR(255),
    "totalLoggedTime" INTEGER,
    "num_stopReq"     INTEGER,
    "num_mps"         INTEGER,
    "num_ips"         INTEGER,
    "num_tbps"        INTEGER,
    "num_ots"         INTEGER,
    "num_af"          INTEGER,
    "num_iko"         INTEGER,
    "num_ar"          INTEGER

);
COMMENT
ON TABLE ld1566 IS 'Electric Motor, Stop Request Event, Counter';
COMMENT
ON COLUMN ld1566."num_stopReq" IS 'motor stop requested';
COMMENT
ON COLUMN ld1566."num_mps" IS 'motor stopped due to motor protection status';
COMMENT
ON COLUMN ld1566."num_ips" IS 'motor stopped due to inverter protection status';
COMMENT
ON COLUMN ld1566."num_tbps" IS 'motor stopped due to traction battery protection status';
COMMENT
ON COLUMN ld1566."num_ots" IS 'motor stopped due to oil temperature status';
COMMENT
ON COLUMN ld1566."num_af" IS 'motor stopped due to autoshutdown function';
COMMENT
ON COLUMN ld1566."num_iko" IS 'motor stopped due to ignition key off';
COMMENT
ON COLUMN ld1566."num_ar" IS 'motor stopped due to armrest raised';

DROP TABLE IF EXISTS ld1568 CASCADE;
CREATE TABLE ld1568
(
    id                SERIAL       NOT NULL,
    "chassisId"       VARCHAR(255) NOT NULL,
    created_by        INTEGER,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by        INTEGER,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone          DATE         NOT NULL,
    "timeStampAtZone" VARCHAR(255),
    "timeZone"        VARCHAR(255),
    "timeStamp"       VARCHAR(255),
    "processedAt"     VARCHAR(255),
    "totalLoggedTime" INTEGER,
    "ocr_bt0n10sec"   INTEGER,
    "ocr_bt10n20sec"  INTEGER,
    "ocr_bt20n30sec"  INTEGER,
    "ocr_bt30n60sec"  INTEGER,
    "ocr_bt60n90sec"  INTEGER,
    "ocr_bt90n120sec" INTEGER,
    "ocr_bt2n3min"    INTEGER,
    "ocr_bt3n4min"    INTEGER,
    "ocr_bt4n5min"    INTEGER,
    "ocr_bt5n10min"   INTEGER,
    "ocr_bt10n15min"  INTEGER,
    "ocr_bt15n20min"  INTEGER,
    "ocr_bt20n30min"  INTEGER,
    "ocr_bt30n45min"  INTEGER,
    "ocr_bt45n60min"  INTEGER,
    "ocr_bt60n90min"  INTEGER,
    "ocr_bt90n120min" INTEGER,
    "ocr_bt2n3h"      INTEGER,
    "ocr_bt3n4h"      INTEGER,
    "ocr_gt4h"        INTEGER
);
COMMENT
ON TABLE ld1568 IS 'Electric Motor Restart, Counter, Time Distribution';

DROP TABLE IF EXISTS ld1569 CASCADE;
CREATE TABLE ld1569
(
    id                SERIAL       NOT NULL,
    "chassisId"       VARCHAR(255) NOT NULL,
    created_by        INTEGER,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by        INTEGER,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone          DATE         NOT NULL,
    "timeStampAtZone" VARCHAR(255),
    "timeZone"        VARCHAR(255),
    "timeStamp"       VARCHAR(255),
    "processedAt"     VARCHAR(255),
    "totalLoggedTime" INTEGER,
    "ofsTemp"         INTEGER,
    "refTemp"         INTEGER,
    "time_lt80"       INTEGER,
    "time_bt80n81"    INTEGER,
    "time_bt81n82"    INTEGER,
    "time_bt82n83"    INTEGER,
    "time_bt83n84"    INTEGER,
    "time_bt84n85"    INTEGER,
    "time_bt85n86"    INTEGER,
    "time_bt86n87"    INTEGER,
    "time_bt87n88"    INTEGER,
    "time_bt88n89"    INTEGER,
    "time_bt89n90"    INTEGER,
    "time_bt90n91"    INTEGER,
    "time_bt91n92"    INTEGER,
    "time_bt92n93"    INTEGER,
    "time_bt93n94"    INTEGER,
    "time_bt94n95"    INTEGER,
    "time_bt95n96"    INTEGER,
    "time_bt96n97"    INTEGER,
    "time_bt97n98"    INTEGER,
    "time_bt98n99"    INTEGER,
    "time_bt99n100"   INTEGER,
    "time_gt100"      INTEGER

);
COMMENT
ON TABLE ld1569 IS 'Electrical Motor Temperature, High range, Time Distribution';

DROP TABLE IF EXISTS ld1570 CASCADE;
CREATE TABLE ld1570
(
    id                SERIAL       NOT NULL,
    "chassisId"       VARCHAR(255) NOT NULL,
    created_by        INTEGER,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by        INTEGER,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone          DATE         NOT NULL,
    "timeStampAtZone" VARCHAR(255),
    "timeZone"        VARCHAR(255),
    "timeStamp"       VARCHAR(255),
    "processedAt"     VARCHAR(255),
    "totalLoggedTime" INTEGER,
    "ofsTemp"         INTEGER,
    "refTemp"         INTEGER,
    "time_lt0"        INTEGER,
    "time_bt0n1"      INTEGER,
    "time_bt1n2"      INTEGER,
    "time_bt2n3"      INTEGER,
    "time_bt3n4"      INTEGER,
    "time_bt4n5"      INTEGER,
    "time_bt5n6"      INTEGER,
    "time_bt6n7"      INTEGER,
    "time_bt7n8"      INTEGER,
    "time_bt8n9"      INTEGER,
    "time_bt9n10"     INTEGER,
    "time_bt10n11"    INTEGER,
    "time_bt11n12"    INTEGER,
    "time_bt12n13"    INTEGER,
    "time_bt13n14"    INTEGER,
    "time_bt14n15"    INTEGER,
    "time_bt15n16"    INTEGER,
    "time_bt16n17"    INTEGER,
    "time_bt17n18"    INTEGER,
    "time_bt18n19"    INTEGER,
    "time_bt19n20"    INTEGER,
    "time_gt20"       INTEGER

);
COMMENT
ON TABLE ld1570 IS 'Electrical Motor Temperature, Low Range, Time Distribution';

DROP TABLE IF EXISTS ld1560 CASCADE;
CREATE TABLE ld1560
(
    id                SERIAL       NOT NULL,
    "chassisId"       VARCHAR(255) NOT NULL,
    created_by        INTEGER,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by        INTEGER,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone          DATE         NOT NULL,
    "timeStampAtZone" VARCHAR(255),
    "timeZone"        VARCHAR(255),
    "timeStamp"       VARCHAR(255),
    "processedAt"     VARCHAR(255),
    "totalLoggedTime" INTEGER,
    "ofsTemp"         INTEGER,
    "refTemp"         INTEGER,
    "time_lt0"        INTEGER,
    "time_bt0n5"      INTEGER,
    "time_bt5n10"     INTEGER,
    "time_bt10n15"    INTEGER,
    "time_bt15n20"    INTEGER,
    "time_bt20n25"    INTEGER,
    "time_bt25n30"    INTEGER,
    "time_bt30n35"    INTEGER,
    "time_bt35n40"    INTEGER,
    "time_bt40n45"    INTEGER,
    "time_bt45n50"    INTEGER,
    "time_bt50n55"    INTEGER,
    "time_bt55n60"    INTEGER,
    "time_bt60n65"    INTEGER,
    "time_bt65n70"    INTEGER,
    "time_bt70n75"    INTEGER,
    "time_bt75n80"    INTEGER,
    "time_bt80n85"    INTEGER,
    "time_bt85n90"    INTEGER,
    "time_bt90n95"    INTEGER,
    "time_bt95n100"   INTEGER,
    "time_gt100"      INTEGER

);
COMMENT
ON TABLE ld1560 IS 'DCDC Converter temperature distribution (full range)';

DROP TABLE IF EXISTS ld1558 CASCADE;
CREATE TABLE ld1558
(
    id                        SERIAL       NOT NULL,
    "chassisId"               VARCHAR(255) NOT NULL,
    created_by                INTEGER,
    created_at                TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by                INTEGER,
    updated_at                TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone                  DATE         NOT NULL,
    "timeStampAtZone"         VARCHAR(255),
    "timeZone"                VARCHAR(255),
    "timeStamp"               VARCHAR(255),
    "processedAt"             VARCHAR(255),
    "totalLoggedTime"         INTEGER,
    "ocrChargeStart_bt0n5"    INTEGER,
    "ocrChargeStart_bt5n10"   INTEGER,
    "ocrChargeStart_bt10n15"  INTEGER,
    "ocrChargeStart_bt15n20"  INTEGER,
    "ocrChargeStart_bt20n25"  INTEGER,
    "ocrChargeStart_bt25n30"  INTEGER,
    "ocrChargeStart_bt30n35"  INTEGER,
    "ocrChargeStart_bt35n40"  INTEGER,
    "ocrChargeStart_bt40n45"  INTEGER,
    "ocrChargeStart_bt45n50"  INTEGER,
    "ocrChargeStart_bt50n55"  INTEGER,
    "ocrChargeStart_bt55n60"  INTEGER,
    "ocrChargeStart_bt60n65"  INTEGER,
    "ocrChargeStart_bt65n70"  INTEGER,
    "ocrChargeStart_bt70n75"  INTEGER,
    "ocrChargeStart_bt75n80"  INTEGER,
    "ocrChargeStart_bt80n85"  INTEGER,
    "ocrChargeStart_bt85n90"  INTEGER,
    "ocrChargeStart_bt90n95"  INTEGER,
    "ocrChargeStart_bt95n100" INTEGER,
    "ocrChargeStop_bt0n5"     INTEGER,
    "ocrChargeStop_bt5n10"    INTEGER,
    "ocrChargeStop_bt10n15"   INTEGER,
    "ocrChargeStop_bt15n20"   INTEGER,
    "ocrChargeStop_bt20n25"   INTEGER,
    "ocrChargeStop_bt25n30"   INTEGER,
    "ocrChargeStop_bt30n35"   INTEGER,
    "ocrChargeStop_bt35n40"   INTEGER,
    "ocrChargeStop_bt40n45"   INTEGER,
    "ocrChargeStop_bt45n50"   INTEGER,
    "ocrChargeStop_bt50n55"   INTEGER,
    "ocrChargeStop_bt55n60"   INTEGER,
    "ocrChargeStop_bt60n65"   INTEGER,
    "ocrChargeStop_bt65n70"   INTEGER,
    "ocrChargeStop_bt70n75"   INTEGER,
    "ocrChargeStop_bt75n80"   INTEGER,
    "ocrChargeStop_bt80n85"   INTEGER,
    "ocrChargeStop_bt85n90"   INTEGER,
    "ocrChargeStop_bt90n95"   INTEGER,
    "ocrChargeStop_bt95n100"  INTEGER

);
COMMENT
ON TABLE ld1558 IS 'Traction battery SoC distribution fast charge started or stopped';

DROP TABLE IF EXISTS ld1559 CASCADE;
CREATE TABLE ld1559
(
    id                        SERIAL       NOT NULL,
    "chassisId"               VARCHAR(255) NOT NULL,
    created_by                INTEGER,
    created_at                TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by                INTEGER,
    updated_at                TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone                  DATE         NOT NULL,
    "timeStampAtZone"         VARCHAR(255),
    "timeZone"                VARCHAR(255),
    "timeStamp"               VARCHAR(255),
    "processedAt"             VARCHAR(255),
    "totalLoggedTime"         INTEGER,
    "ocrChargeStart_bt0n5"    INTEGER,
    "ocrChargeStart_bt5n10"   INTEGER,
    "ocrChargeStart_bt10n15"  INTEGER,
    "ocrChargeStart_bt15n20"  INTEGER,
    "ocrChargeStart_bt20n25"  INTEGER,
    "ocrChargeStart_bt25n30"  INTEGER,
    "ocrChargeStart_bt30n35"  INTEGER,
    "ocrChargeStart_bt35n40"  INTEGER,
    "ocrChargeStart_bt40n45"  INTEGER,
    "ocrChargeStart_bt45n50"  INTEGER,
    "ocrChargeStart_bt50n55"  INTEGER,
    "ocrChargeStart_bt55n60"  INTEGER,
    "ocrChargeStart_bt60n65"  INTEGER,
    "ocrChargeStart_bt65n70"  INTEGER,
    "ocrChargeStart_bt70n75"  INTEGER,
    "ocrChargeStart_bt75n80"  INTEGER,
    "ocrChargeStart_bt80n85"  INTEGER,
    "ocrChargeStart_bt85n90"  INTEGER,
    "ocrChargeStart_bt90n95"  INTEGER,
    "ocrChargeStart_bt95n100" INTEGER,
    "ocrChargeStop_bt0n5"     INTEGER,
    "ocrChargeStop_bt5n10"    INTEGER,
    "ocrChargeStop_bt10n15"   INTEGER,
    "ocrChargeStop_bt15n20"   INTEGER,
    "ocrChargeStop_bt20n25"   INTEGER,
    "ocrChargeStop_bt25n30"   INTEGER,
    "ocrChargeStop_bt30n35"   INTEGER,
    "ocrChargeStop_bt35n40"   INTEGER,
    "ocrChargeStop_bt40n45"   INTEGER,
    "ocrChargeStop_bt45n50"   INTEGER,
    "ocrChargeStop_bt50n55"   INTEGER,
    "ocrChargeStop_bt55n60"   INTEGER,
    "ocrChargeStop_bt60n65"   INTEGER,
    "ocrChargeStop_bt65n70"   INTEGER,
    "ocrChargeStop_bt70n75"   INTEGER,
    "ocrChargeStop_bt75n80"   INTEGER,
    "ocrChargeStop_bt80n85"   INTEGER,
    "ocrChargeStop_bt85n90"   INTEGER,
    "ocrChargeStop_bt90n95"   INTEGER,
    "ocrChargeStop_bt95n100"  INTEGER

);
COMMENT
ON TABLE ld1559 IS 'Traction battery SoC distribution slow charge started or stopped';

DROP TABLE IF EXISTS ld1571 CASCADE;
CREATE TABLE ld1571
(
    id                SERIAL       NOT NULL,
    "chassisId"       VARCHAR(255) NOT NULL,
    created_by        INTEGER,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by        INTEGER,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone          DATE         NOT NULL,
    "timeStampAtZone" VARCHAR(255),
    "timeZone"        VARCHAR(255),
    "timeStamp"       VARCHAR(255),
    "processedAt"     VARCHAR(255),
    "totalLoggedTime" INTEGER,
    "ofsTemp"         INTEGER,
    "refTemp"         INTEGER,
    "time_lt0"        INTEGER,
    "time_bt0n5"      INTEGER,
    "time_bt5n10"     INTEGER,
    "time_bt10n15"    INTEGER,
    "time_bt15n20"    INTEGER,
    "time_bt20n25"    INTEGER,
    "time_bt25n30"    INTEGER,
    "time_bt30n35"    INTEGER,
    "time_bt35n40"    INTEGER,
    "time_bt40n45"    INTEGER,
    "time_bt45n50"    INTEGER,
    "time_bt50n55"    INTEGER,
    "time_bt55n60"    INTEGER,
    "time_bt60n65"    INTEGER,
    "time_bt65n70"    INTEGER,
    "time_bt70n75"    INTEGER,
    "time_bt75n80"    INTEGER,
    "time_bt80n85"    INTEGER,
    "time_bt85n90"    INTEGER,
    "time_bt90n95"    INTEGER,
    "time_bt95n100"   INTEGER,
    "time_gt100"      INTEGER

);
COMMENT
ON TABLE ld1571 IS 'On Board Charger temperature distribution (full range)';

DROP TABLE IF EXISTS ld1525 CASCADE;
CREATE TABLE ld1525
(
    id                        SERIAL       NOT NULL,
    "chassisId"               VARCHAR(255) NOT NULL,
    created_by                INTEGER,
    created_at                TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by                INTEGER,
    updated_at                TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone                  DATE         NOT NULL,
    "timeStampAtZone"         VARCHAR(255),
    "timeZone"                VARCHAR(255),
    "timeStamp"               VARCHAR(255),
    "processedAt"             VARCHAR(255),
    "totalLoggedTime"         INTEGER,
    "totalTimeElapsed_off"    INTEGER,
    "totalTimeElapsed_on"     INTEGER,
    "totalEnergyConsumed_off" INTEGER,
    "totalEnergyConsumed_on"  INTEGER

);
COMMENT
ON TABLE ld1525 IS 'Total energy consumed DCDC VS key position';

DROP TABLE IF EXISTS ld1572 CASCADE;
CREATE TABLE ld1572
(
    id                SERIAL       NOT NULL,
    "chassisId"       VARCHAR(255) NOT NULL,
    created_by        INTEGER,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by        INTEGER,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone          DATE         NOT NULL,
    "timeStampAtZone" VARCHAR(255),
    "timeZone"        VARCHAR(255),
    "timeStamp"       VARCHAR(255),
    "processedAt"     VARCHAR(255),
    "totalLoggedTime" INTEGER,
    "ofsTemp"         INTEGER,
    "refTemp"         INTEGER,
    "time_lt80"       INTEGER,
    "time_bt80n81"    INTEGER,
    "time_bt81n82"    INTEGER,
    "time_bt82n83"    INTEGER,
    "time_bt83n84"    INTEGER,
    "time_bt84n85"    INTEGER,
    "time_bt85n86"    INTEGER,
    "time_bt86n87"    INTEGER,
    "time_bt87n88"    INTEGER,
    "time_bt88n89"    INTEGER,
    "time_bt89n90"    INTEGER,
    "time_bt90n91"    INTEGER,
    "time_bt91n92"    INTEGER,
    "time_bt92n93"    INTEGER,
    "time_bt93n94"    INTEGER,
    "time_bt94n95"    INTEGER,
    "time_bt95n96"    INTEGER,
    "time_bt96n97"    INTEGER,
    "time_bt97n98"    INTEGER,
    "time_bt98n99"    INTEGER,
    "time_bt99n100"   INTEGER,
    "time_gt100"      INTEGER

);
COMMENT
ON TABLE ld1572 IS 'On Board Charger temperature distribution (high range)';

DROP TABLE IF EXISTS ld1573 CASCADE;
CREATE TABLE ld1573
(
    id                SERIAL       NOT NULL,
    "chassisId"       VARCHAR(255) NOT NULL,
    created_by        INTEGER,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by        INTEGER,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone          DATE         NOT NULL,
    "timeStampAtZone" VARCHAR(255),
    "timeZone"        VARCHAR(255),
    "timeStamp"       VARCHAR(255),
    "processedAt"     VARCHAR(255),
    "totalLoggedTime" INTEGER,
    "ofsTemp"         INTEGER,
    "refTemp"         INTEGER,
    "time_lt0"        INTEGER,
    "time_bt0n1"      INTEGER,
    "time_bt1n2"      INTEGER,
    "time_bt2n3"      INTEGER,
    "time_bt3n4"      INTEGER,
    "time_bt4n5"      INTEGER,
    "time_bt5n6"      INTEGER,
    "time_bt6n7"      INTEGER,
    "time_bt7n8"      INTEGER,
    "time_bt8n9"      INTEGER,
    "time_bt9n10"     INTEGER,
    "time_bt10n11"    INTEGER,
    "time_bt11n12"    INTEGER,
    "time_bt12n13"    INTEGER,
    "time_bt13n14"    INTEGER,
    "time_bt14n15"    INTEGER,
    "time_bt15n16"    INTEGER,
    "time_bt16n17"    INTEGER,
    "time_bt17n18"    INTEGER,
    "time_bt18n19"    INTEGER,
    "time_bt19n20"    INTEGER,
    "time_gt20"       INTEGER
);
COMMENT
ON TABLE ld1573 IS 'On Board Charger temperature distribution (low range)';

DROP TABLE IF EXISTS ld1539 CASCADE;
CREATE TABLE ld1539
(
    id                SERIAL       NOT NULL,
    "chassisId"       VARCHAR(255) NOT NULL,
    created_by        INTEGER,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by        INTEGER,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone          DATE         NOT NULL,
    "timeStampAtZone" VARCHAR(255),
    "timeZone"        VARCHAR(255),
    "timeStamp"       VARCHAR(255),
    "processedAt"     VARCHAR(255),
    "totalLoggedTime" INTEGER,
    "no0_ct"          VARCHAR(255),
    "no0_mh"          INTEGER,
    "no0_ed"          INTEGER,
    "no1_ct"          VARCHAR(255),
    "no1_mh"          INTEGER,
    "no1_ed"          INTEGER,
    "no2_ct"          VARCHAR(255),
    "no2_mh"          INTEGER,
    "no2_ed"          INTEGER,
    "no3_ct"          VARCHAR(255),
    "no3_mh"          INTEGER,
    "no3_ed"          INTEGER,
    "no4_ct"          VARCHAR(255),
    "no4_mh"          INTEGER,
    "no4_ed"          INTEGER,
    "no5_ct"          VARCHAR(255),
    "no5_mh"          INTEGER,
    "no5_ed"          INTEGER,
    "no6_ct"          VARCHAR(255),
    "no6_mh"          INTEGER,
    "no6_ed"          INTEGER,
    "no7_ct"          VARCHAR(255),
    "no7_mh"          INTEGER,
    "no7_ed"          INTEGER,
    "no8_ct"          VARCHAR(255),
    "no8_mh"          INTEGER,
    "no8_ed"          INTEGER,
    "no9_ct"          VARCHAR(255),
    "no9_mh"          INTEGER,
    "no9_ed"          INTEGER,
    "no10_ct"         VARCHAR(255),
    "no10_mh"         INTEGER,
    "no10_ed"         INTEGER,
    "no11_ct"         VARCHAR(255),
    "no11_mh"         INTEGER,
    "no11_ed"         INTEGER,
    "no12_ct"         VARCHAR(255),
    "no12_mh"         INTEGER,
    "no12_ed"         INTEGER,
    "no13_ct"         VARCHAR(255),
    "no13_mh"         INTEGER,
    "no13_ed"         INTEGER,
    "no14_ct"         VARCHAR(255),
    "no14_mh"         INTEGER,
    "no14_ed"         INTEGER,
    "no15_ct"         VARCHAR(255),
    "no15_mh"         INTEGER,
    "no15_ed"         INTEGER,
    "no16_ct"         VARCHAR(255),
    "no16_mh"         INTEGER,
    "no16_ed"         INTEGER,
    "no17_ct"         VARCHAR(255),
    "no17_mh"         INTEGER,
    "no17_ed"         INTEGER,
    "no18_ct"         VARCHAR(255),
    "no18_mh"         INTEGER,
    "no18_ed"         INTEGER,
    "no19_ct"         VARCHAR(255),
    "no19_mh"         INTEGER,
    "no19_ed"         INTEGER,
    "no0_od"          NUMERIC(24, 2),
    "no1_od"          NUMERIC(24, 2),
    "no2_od"          NUMERIC(24, 2),
    "no3_od"          NUMERIC(24, 2),
    "no4_od"          NUMERIC(24, 2),
    "no5_od"          NUMERIC(24, 2),
    "no6_od"          NUMERIC(24, 2),
    "no7_od"          NUMERIC(24, 2),
    "no8_od"          NUMERIC(24, 2),
    "no9_od"          NUMERIC(24, 2),
    "no10_od"         NUMERIC(24, 2),
    "no11_od"         NUMERIC(24, 2),
    "no12_od"         NUMERIC(24, 2),
    "no13_od"         NUMERIC(24, 2),
    "no14_od"         NUMERIC(24, 2),
    "no15_od"         NUMERIC(24, 2),
    "no16_od"         NUMERIC(24, 2),
    "no17_od"         NUMERIC(24, 2),
    "no18_od"         NUMERIC(24, 2),
    "no19_od"         NUMERIC(24, 2)

);
COMMENT
ON TABLE ld1539 IS 'Maximum voltage on DC link';

DROP TABLE IF EXISTS ld1540 CASCADE;
CREATE TABLE ld1540
(
    id                SERIAL       NOT NULL,
    "chassisId"       VARCHAR(255) NOT NULL,
    created_by        INTEGER,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by        INTEGER,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone          DATE         NOT NULL,
    "timeStampAtZone" VARCHAR(255),
    "timeZone"        VARCHAR(255),
    "timeStamp"       VARCHAR(255),
    "processedAt"     VARCHAR(255),
    "totalLoggedTime" INTEGER,
    "no0_ct"          VARCHAR(255),
    "no0_mh"          INTEGER,
    "no0_ed"          INTEGER,
    "no1_ct"          VARCHAR(255),
    "no1_mh"          INTEGER,
    "no1_ed"          INTEGER,
    "no2_ct"          VARCHAR(255),
    "no2_mh"          INTEGER,
    "no2_ed"          INTEGER,
    "no3_ct"          VARCHAR(255),
    "no3_mh"          INTEGER,
    "no3_ed"          INTEGER,
    "no4_ct"          VARCHAR(255),
    "no4_mh"          INTEGER,
    "no4_ed"          INTEGER,
    "no5_ct"          VARCHAR(255),
    "no5_mh"          INTEGER,
    "no5_ed"          INTEGER,
    "no6_ct"          VARCHAR(255),
    "no6_mh"          INTEGER,
    "no6_ed"          INTEGER,
    "no7_ct"          VARCHAR(255),
    "no7_mh"          INTEGER,
    "no7_ed"          INTEGER,
    "no8_ct"          VARCHAR(255),
    "no8_mh"          INTEGER,
    "no8_ed"          INTEGER,
    "no9_ct"          VARCHAR(255),
    "no9_mh"          INTEGER,
    "no9_ed"          INTEGER,
    "no10_ct"         VARCHAR(255),
    "no10_mh"         INTEGER,
    "no10_ed"         INTEGER,
    "no11_ct"         VARCHAR(255),
    "no11_mh"         INTEGER,
    "no11_ed"         INTEGER,
    "no12_ct"         VARCHAR(255),
    "no12_mh"         INTEGER,
    "no12_ed"         INTEGER,
    "no13_ct"         VARCHAR(255),
    "no13_mh"         INTEGER,
    "no13_ed"         INTEGER,
    "no14_ct"         VARCHAR(255),
    "no14_mh"         INTEGER,
    "no14_ed"         INTEGER,
    "no15_ct"         VARCHAR(255),
    "no15_mh"         INTEGER,
    "no15_ed"         INTEGER,
    "no16_ct"         VARCHAR(255),
    "no16_mh"         INTEGER,
    "no16_ed"         INTEGER,
    "no17_ct"         VARCHAR(255),
    "no17_mh"         INTEGER,
    "no17_ed"         INTEGER,
    "no18_ct"         VARCHAR(255),
    "no18_mh"         INTEGER,
    "no18_ed"         INTEGER,
    "no19_ct"         VARCHAR(255),
    "no19_mh"         INTEGER,
    "no19_ed"         INTEGER,
    "no0_od"          NUMERIC(24, 2),
    "no1_od"          NUMERIC(24, 2),
    "no2_od"          NUMERIC(24, 2),
    "no3_od"          NUMERIC(24, 2),
    "no4_od"          NUMERIC(24, 2),
    "no5_od"          NUMERIC(24, 2),
    "no6_od"          NUMERIC(24, 2),
    "no7_od"          NUMERIC(24, 2),
    "no8_od"          NUMERIC(24, 2),
    "no9_od"          NUMERIC(24, 2),
    "no10_od"         NUMERIC(24, 2),
    "no11_od"         NUMERIC(24, 2),
    "no12_od"         NUMERIC(24, 2),
    "no13_od"         NUMERIC(24, 2),
    "no14_od"         NUMERIC(24, 2),
    "no15_od"         NUMERIC(24, 2),
    "no16_od"         NUMERIC(24, 2),
    "no17_od"         NUMERIC(24, 2),
    "no18_od"         NUMERIC(24, 2),
    "no19_od"         NUMERIC(24, 2)

);
COMMENT
ON TABLE ld1540 IS 'Minimum voltage on DC link';

DROP TABLE IF EXISTS ld1543 CASCADE;
CREATE TABLE ld1543
(
    id                SERIAL       NOT NULL,
    "chassisId"       VARCHAR(255) NOT NULL,
    created_by        INTEGER,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by        INTEGER,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone          DATE         NOT NULL,
    "timeStampAtZone" VARCHAR(255),
    "timeZone"        VARCHAR(255),
    "timeStamp"       VARCHAR(255),
    "processedAt"     VARCHAR(255),
    "totalLoggedTime" INTEGER,
    "ofsTemp"         INTEGER,
    "refTemp"         INTEGER,
    "time_lt0"        INTEGER,
    "time_bt0n5"      INTEGER,
    "time_bt5n10"     INTEGER,
    "time_bt10n15"    INTEGER,
    "time_bt15n20"    INTEGER,
    "time_bt20n25"    INTEGER,
    "time_bt25n30"    INTEGER,
    "time_bt30n35"    INTEGER,
    "time_bt35n40"    INTEGER,
    "time_bt40n45"    INTEGER,
    "time_bt45n50"    INTEGER,
    "time_bt50n55"    INTEGER,
    "time_bt55n60"    INTEGER,
    "time_bt60n65"    INTEGER,
    "time_bt65n70"    INTEGER,
    "time_bt70n75"    INTEGER,
    "time_bt75n80"    INTEGER,
    "time_bt80n85"    INTEGER,
    "time_bt85n90"    INTEGER,
    "time_bt90n95"    INTEGER,
    "time_bt95n100"   INTEGER,
    "time_gt100"      INTEGER

);
COMMENT
ON TABLE ld1543 IS 'Traction battery cell average temperature distribution (full range)';

DROP TABLE IF EXISTS ld1546 CASCADE;
CREATE TABLE ld1546
(
    id                SERIAL       NOT NULL,
    "chassisId"       VARCHAR(255) NOT NULL,
    created_by        INTEGER,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by        INTEGER,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone          DATE         NOT NULL,
    "timeStampAtZone" VARCHAR(255),
    "timeZone"        VARCHAR(255),
    "timeStamp"       VARCHAR(255),
    "processedAt"     VARCHAR(255),
    "totalLoggedTime" INTEGER,
    "no0_ct"          VARCHAR(255),
    "no0_mh"          INTEGER,
    "no0_ed"          INTEGER,
    "no1_ct"          VARCHAR(255),
    "no1_mh"          INTEGER,
    "no1_ed"          INTEGER,
    "no2_ct"          VARCHAR(255),
    "no2_mh"          INTEGER,
    "no2_ed"          INTEGER,
    "no3_ct"          VARCHAR(255),
    "no3_mh"          INTEGER,
    "no3_ed"          INTEGER,
    "no4_ct"          VARCHAR(255),
    "no4_mh"          INTEGER,
    "no4_ed"          INTEGER,
    "no5_ct"          VARCHAR(255),
    "no5_mh"          INTEGER,
    "no5_ed"          INTEGER,
    "no6_ct"          VARCHAR(255),
    "no6_mh"          INTEGER,
    "no6_ed"          INTEGER,
    "no7_ct"          VARCHAR(255),
    "no7_mh"          INTEGER,
    "no7_ed"          INTEGER,
    "no8_ct"          VARCHAR(255),
    "no8_mh"          INTEGER,
    "no8_ed"          INTEGER,
    "no9_ct"          VARCHAR(255),
    "no9_mh"          INTEGER,
    "no9_ed"          INTEGER,
    "no10_ct"         VARCHAR(255),
    "no10_mh"         INTEGER,
    "no10_ed"         INTEGER,
    "no11_ct"         VARCHAR(255),
    "no11_mh"         INTEGER,
    "no11_ed"         INTEGER,
    "no12_ct"         VARCHAR(255),
    "no12_mh"         INTEGER,
    "no12_ed"         INTEGER,
    "no13_ct"         VARCHAR(255),
    "no13_mh"         INTEGER,
    "no13_ed"         INTEGER,
    "no14_ct"         VARCHAR(255),
    "no14_mh"         INTEGER,
    "no14_ed"         INTEGER,
    "no15_ct"         VARCHAR(255),
    "no15_mh"         INTEGER,
    "no15_ed"         INTEGER,
    "no16_ct"         VARCHAR(255),
    "no16_mh"         INTEGER,
    "no16_ed"         INTEGER,
    "no17_ct"         VARCHAR(255),
    "no17_mh"         INTEGER,
    "no17_ed"         INTEGER,
    "no18_ct"         VARCHAR(255),
    "no18_mh"         INTEGER,
    "no18_ed"         INTEGER,
    "no19_ct"         VARCHAR(255),
    "no19_mh"         INTEGER,
    "no19_ed"         INTEGER,
    "no0_od"          NUMERIC(24, 2),
    "no1_od"          NUMERIC(24, 2),
    "no2_od"          NUMERIC(24, 2),
    "no3_od"          NUMERIC(24, 2),
    "no4_od"          NUMERIC(24, 2),
    "no5_od"          NUMERIC(24, 2),
    "no6_od"          NUMERIC(24, 2),
    "no7_od"          NUMERIC(24, 2),
    "no8_od"          NUMERIC(24, 2),
    "no9_od"          NUMERIC(24, 2),
    "no10_od"         NUMERIC(24, 2),
    "no11_od"         NUMERIC(24, 2),
    "no12_od"         NUMERIC(24, 2),
    "no13_od"         NUMERIC(24, 2),
    "no14_od"         NUMERIC(24, 2),
    "no15_od"         NUMERIC(24, 2),
    "no16_od"         NUMERIC(24, 2),
    "no17_od"         NUMERIC(24, 2),
    "no18_od"         NUMERIC(24, 2),
    "no19_od"         NUMERIC(24, 2)
);
COMMENT
ON TABLE ld1546 IS 'Traction battery disconnected unexpectedly event occurences';

DROP TABLE IF EXISTS ld1547 CASCADE;
CREATE TABLE ld1547
(
    id                SERIAL       NOT NULL,
    "chassisId"       VARCHAR(255) NOT NULL,
    created_by        INTEGER,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by        INTEGER,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone          DATE         NOT NULL,
    "timeStampAtZone" VARCHAR(255),
    "timeZone"        VARCHAR(255),
    "timeStamp"       VARCHAR(255),
    "processedAt"     VARCHAR(255),
    "totalLoggedTime" INTEGER,
    "time_lt80"       INTEGER,
    "time_bt80n81"    INTEGER,
    "time_bt81n82"    INTEGER,
    "time_bt82n83"    INTEGER,
    "time_bt83n84"    INTEGER,
    "time_bt84n85"    INTEGER,
    "time_bt85n86"    INTEGER,
    "time_bt86n87"    INTEGER,
    "time_bt87n88"    INTEGER,
    "time_bt88n89"    INTEGER,
    "time_bt89n90"    INTEGER,
    "time_bt90n91"    INTEGER,
    "time_bt91n92"    INTEGER,
    "time_bt92n93"    INTEGER,
    "time_bt93n94"    INTEGER,
    "time_bt94n95"    INTEGER,
    "time_bt95n96"    INTEGER,
    "time_bt96n97"    INTEGER,
    "time_bt97n98"    INTEGER,
    "time_bt98n99"    INTEGER,
    "time_bt99n100"   INTEGER

);
COMMENT
ON TABLE ld1547 IS 'Traction battery SoC distribution (high range)';

DROP TABLE IF EXISTS ld1548 CASCADE;
CREATE TABLE ld1548
(
    id                SERIAL       NOT NULL,
    "chassisId"       VARCHAR(255) NOT NULL,
    created_by        INTEGER,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by        INTEGER,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone          DATE         NOT NULL,
    "timeStampAtZone" VARCHAR(255),
    "timeZone"        VARCHAR(255),
    "timeStamp"       VARCHAR(255),
    "processedAt"     VARCHAR(255),
    "totalLoggedTime" INTEGER,
    "time_lt0"        INTEGER,
    "time_bt0n1"      INTEGER,
    "time_bt1n2"      INTEGER,
    "time_bt2n3"      INTEGER,
    "time_bt3n4"      INTEGER,
    "time_bt4n5"      INTEGER,
    "time_bt5n6"      INTEGER,
    "time_bt6n7"      INTEGER,
    "time_bt7n8"      INTEGER,
    "time_bt8n9"      INTEGER,
    "time_bt9n10"     INTEGER,
    "time_bt10n11"    INTEGER,
    "time_bt11n12"    INTEGER,
    "time_bt12n13"    INTEGER,
    "time_bt13n14"    INTEGER,
    "time_bt14n15"    INTEGER,
    "time_bt15n16"    INTEGER,
    "time_bt16n17"    INTEGER,
    "time_bt17n18"    INTEGER,
    "time_bt18n19"    INTEGER,
    "time_bt19n20"    INTEGER
);
COMMENT
ON TABLE ld1548 IS 'Traction battery SoC distribution (low range)';

DROP TABLE IF EXISTS ld1554 CASCADE;
CREATE TABLE ld1554
(
    id                SERIAL       NOT NULL,
    "chassisId"       VARCHAR(255) NOT NULL,
    created_by        INTEGER,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by        INTEGER,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone          DATE         NOT NULL,
    "timeStampAtZone" VARCHAR(255),
    "timeZone"        VARCHAR(255),
    "timeStamp"       VARCHAR(255),
    "processedAt"     VARCHAR(255),
    "totalLoggedTime" INTEGER,
    "no0_ct"          VARCHAR(255),
    "no0_mh"          INTEGER,
    "no0_ed"          INTEGER,
    "no1_ct"          VARCHAR(255),
    "no1_mh"          INTEGER,
    "no1_ed"          INTEGER,
    "no2_ct"          VARCHAR(255),
    "no2_mh"          INTEGER,
    "no2_ed"          INTEGER,
    "no3_ct"          VARCHAR(255),
    "no3_mh"          INTEGER,
    "no3_ed"          INTEGER,
    "no4_ct"          VARCHAR(255),
    "no4_mh"          INTEGER,
    "no4_ed"          INTEGER,
    "no5_ct"          VARCHAR(255),
    "no5_mh"          INTEGER,
    "no5_ed"          INTEGER,
    "no6_ct"          VARCHAR(255),
    "no6_mh"          INTEGER,
    "no6_ed"          INTEGER,
    "no7_ct"          VARCHAR(255),
    "no7_mh"          INTEGER,
    "no7_ed"          INTEGER,
    "no8_ct"          VARCHAR(255),
    "no8_mh"          INTEGER,
    "no8_ed"          INTEGER,
    "no9_ct"          VARCHAR(255),
    "no9_mh"          INTEGER,
    "no9_ed"          INTEGER,
    "no10_ct"         VARCHAR(255),
    "no10_mh"         INTEGER,
    "no10_ed"         INTEGER,
    "no11_ct"         VARCHAR(255),
    "no11_mh"         INTEGER,
    "no11_ed"         INTEGER,
    "no12_ct"         VARCHAR(255),
    "no12_mh"         INTEGER,
    "no12_ed"         INTEGER,
    "no13_ct"         VARCHAR(255),
    "no13_mh"         INTEGER,
    "no13_ed"         INTEGER,
    "no14_ct"         VARCHAR(255),
    "no14_mh"         INTEGER,
    "no14_ed"         INTEGER,
    "no15_ct"         VARCHAR(255),
    "no15_mh"         INTEGER,
    "no15_ed"         INTEGER,
    "no16_ct"         VARCHAR(255),
    "no16_mh"         INTEGER,
    "no16_ed"         INTEGER,
    "no17_ct"         VARCHAR(255),
    "no17_mh"         INTEGER,
    "no17_ed"         INTEGER,
    "no18_ct"         VARCHAR(255),
    "no18_mh"         INTEGER,
    "no18_ed"         INTEGER,
    "no19_ct"         VARCHAR(255),
    "no19_mh"         INTEGER,
    "no19_ed"         INTEGER,
    "no0_od"          NUMERIC(24, 2),
    "no1_od"          NUMERIC(24, 2),
    "no2_od"          NUMERIC(24, 2),
    "no3_od"          NUMERIC(24, 2),
    "no4_od"          NUMERIC(24, 2),
    "no5_od"          NUMERIC(24, 2),
    "no6_od"          NUMERIC(24, 2),
    "no7_od"          NUMERIC(24, 2),
    "no8_od"          NUMERIC(24, 2),
    "no9_od"          NUMERIC(24, 2),
    "no10_od"         NUMERIC(24, 2),
    "no11_od"         NUMERIC(24, 2),
    "no12_od"         NUMERIC(24, 2),
    "no13_od"         NUMERIC(24, 2),
    "no14_od"         NUMERIC(24, 2),
    "no15_od"         NUMERIC(24, 2),
    "no16_od"         NUMERIC(24, 2),
    "no17_od"         NUMERIC(24, 2),
    "no18_od"         NUMERIC(24, 2),
    "no19_od"         NUMERIC(24, 2)
);
COMMENT
ON TABLE ld1554 IS 'Maximum charging current from traction battery';

DROP TABLE IF EXISTS ld1555 CASCADE;
CREATE TABLE ld1555
(
    id                SERIAL       NOT NULL,
    "chassisId"       VARCHAR(255) NOT NULL,
    created_by        INTEGER,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by        INTEGER,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone          DATE         NOT NULL,
    "timeStampAtZone" VARCHAR(255),
    "timeZone"        VARCHAR(255),
    "timeStamp"       VARCHAR(255),
    "processedAt"     VARCHAR(255),
    "totalLoggedTime" INTEGER,
    "no0_ct"          VARCHAR(255),
    "no0_mh"          INTEGER,
    "no0_ed"          INTEGER,
    "no1_ct"          VARCHAR(255),
    "no1_mh"          INTEGER,
    "no1_ed"          INTEGER,
    "no2_ct"          VARCHAR(255),
    "no2_mh"          INTEGER,
    "no2_ed"          INTEGER,
    "no3_ct"          VARCHAR(255),
    "no3_mh"          INTEGER,
    "no3_ed"          INTEGER,
    "no4_ct"          VARCHAR(255),
    "no4_mh"          INTEGER,
    "no4_ed"          INTEGER,
    "no5_ct"          VARCHAR(255),
    "no5_mh"          INTEGER,
    "no5_ed"          INTEGER,
    "no6_ct"          VARCHAR(255),
    "no6_mh"          INTEGER,
    "no6_ed"          INTEGER,
    "no7_ct"          VARCHAR(255),
    "no7_mh"          INTEGER,
    "no7_ed"          INTEGER,
    "no8_ct"          VARCHAR(255),
    "no8_mh"          INTEGER,
    "no8_ed"          INTEGER,
    "no9_ct"          VARCHAR(255),
    "no9_mh"          INTEGER,
    "no9_ed"          INTEGER,
    "no10_ct"         VARCHAR(255),
    "no10_mh"         INTEGER,
    "no10_ed"         INTEGER,
    "no11_ct"         VARCHAR(255),
    "no11_mh"         INTEGER,
    "no11_ed"         INTEGER,
    "no12_ct"         VARCHAR(255),
    "no12_mh"         INTEGER,
    "no12_ed"         INTEGER,
    "no13_ct"         VARCHAR(255),
    "no13_mh"         INTEGER,
    "no13_ed"         INTEGER,
    "no14_ct"         VARCHAR(255),
    "no14_mh"         INTEGER,
    "no14_ed"         INTEGER,
    "no15_ct"         VARCHAR(255),
    "no15_mh"         INTEGER,
    "no15_ed"         INTEGER,
    "no16_ct"         VARCHAR(255),
    "no16_mh"         INTEGER,
    "no16_ed"         INTEGER,
    "no17_ct"         VARCHAR(255),
    "no17_mh"         INTEGER,
    "no17_ed"         INTEGER,
    "no18_ct"         VARCHAR(255),
    "no18_mh"         INTEGER,
    "no18_ed"         INTEGER,
    "no19_ct"         VARCHAR(255),
    "no19_mh"         INTEGER,
    "no19_ed"         INTEGER,
    "no0_od"          NUMERIC(24, 2),
    "no1_od"          NUMERIC(24, 2),
    "no2_od"          NUMERIC(24, 2),
    "no3_od"          NUMERIC(24, 2),
    "no4_od"          NUMERIC(24, 2),
    "no5_od"          NUMERIC(24, 2),
    "no6_od"          NUMERIC(24, 2),
    "no7_od"          NUMERIC(24, 2),
    "no8_od"          NUMERIC(24, 2),
    "no9_od"          NUMERIC(24, 2),
    "no10_od"         NUMERIC(24, 2),
    "no11_od"         NUMERIC(24, 2),
    "no12_od"         NUMERIC(24, 2),
    "no13_od"         NUMERIC(24, 2),
    "no14_od"         NUMERIC(24, 2),
    "no15_od"         NUMERIC(24, 2),
    "no16_od"         NUMERIC(24, 2),
    "no17_od"         NUMERIC(24, 2),
    "no18_od"         NUMERIC(24, 2),
    "no19_od"         NUMERIC(24, 2)
);
COMMENT
ON TABLE ld1555 IS 'Maximum discharging current from traction battery';

DROP TABLE IF EXISTS ld1574 CASCADE;
CREATE TABLE ld1574
(
    id                SERIAL       NOT NULL,
    "chassisId"       VARCHAR(255) NOT NULL,
    created_by        INTEGER,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by        INTEGER,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone          DATE         NOT NULL,
    "timeStampAtZone" VARCHAR(255),
    "timeZone"        VARCHAR(255),
    "timeStamp"       VARCHAR(255),
    "processedAt"     VARCHAR(255),
    "totalLoggedTime" INTEGER,
    "ofsTemp"         INTEGER,
    "refTemp"         INTEGER,
    "time_lt80"       INTEGER,
    "time_bt80n81"    INTEGER,
    "time_bt81n82"    INTEGER,
    "time_bt82n83"    INTEGER,
    "time_bt83n84"    INTEGER,
    "time_bt84n85"    INTEGER,
    "time_bt85n86"    INTEGER,
    "time_bt86n87"    INTEGER,
    "time_bt87n88"    INTEGER,
    "time_bt88n89"    INTEGER,
    "time_bt89n90"    INTEGER,
    "time_bt90n91"    INTEGER,
    "time_bt91n92"    INTEGER,
    "time_bt92n93"    INTEGER,
    "time_bt93n94"    INTEGER,
    "time_bt94n95"    INTEGER,
    "time_bt95n96"    INTEGER,
    "time_bt96n97"    INTEGER,
    "time_bt97n98"    INTEGER,
    "time_bt98n99"    INTEGER,
    "time_bt99n100"   INTEGER,
    "time_gt100"      INTEGER
);
COMMENT
ON TABLE ld1574 IS 'Traction battery cell average temperature distribution (high range)';

DROP TABLE IF EXISTS ld1575 CASCADE;
CREATE TABLE ld1575
(
    id                SERIAL       NOT NULL,
    "chassisId"       VARCHAR(255) NOT NULL,
    created_by        INTEGER,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by        INTEGER,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    day_zone          DATE         NOT NULL,
    "timeStampAtZone" VARCHAR(255),
    "timeZone"        VARCHAR(255),
    "timeStamp"       VARCHAR(255),
    "processedAt"     VARCHAR(255),
    "totalLoggedTime" INTEGER,
    "ofsTemp"         INTEGER,
    "refTemp"         INTEGER,
    "time_lt0"        INTEGER,
    "time_bt0n1"      INTEGER,
    "time_bt1n2"      INTEGER,
    "time_bt2n3"      INTEGER,
    "time_bt3n4"      INTEGER,
    "time_bt4n5"      INTEGER,
    "time_bt5n6"      INTEGER,
    "time_bt6n7"      INTEGER,
    "time_bt7n8"      INTEGER,
    "time_bt8n9"      INTEGER,
    "time_bt9n10"     INTEGER,
    "time_bt10n11"    INTEGER,
    "time_bt11n12"    INTEGER,
    "time_bt12n13"    INTEGER,
    "time_bt13n14"    INTEGER,
    "time_bt14n15"    INTEGER,
    "time_bt15n16"    INTEGER,
    "time_bt16n17"    INTEGER,
    "time_bt17n18"    INTEGER,
    "time_bt18n19"    INTEGER,
    "time_bt19n20"    INTEGER,
    "time_gt20"       INTEGER
);
COMMENT
ON TABLE ld1575 IS 'Traction battery cell average temperature distribution (low range)';

    