---
apiVersion: v1
kind: Service
metadata:
  name: mysql-expose
spec:
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: mysql-db
    app.kubernetes.io/name: mysql
  type: LoadBalancer
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306